#!/bin/bash

# send to ip address of worker node 2
#con=$1 # number of concurrency requests
duration=60
numOfRequest=50000
Port=$1
con=$2
eva_case=$3
HOSTNAMES=("node1" "node2" "node3")

rm eva_all_$eva_case
touch eva_all_$eva_case

for HOST in ${HOSTNAMES[@]}
do
        echo $HOST
        rm log_$HOST
        ab -c $con -t $duration -n $numOfRequest http://$HOST:$Port/ > log_$HOST &
done

sleep 70

for HOST in ${HOSTNAMES[@]}
do

        sum=0
        sum_mean=0
        sum_sd=0
        nr=`cat log_$HOST | grep "Requests per second" | sed 's/[^0-9.]*//g'`

        sum=`echo $sum + $nr | bc`

        totaltime=`cat log_$HOST | grep "Total:"`

        mean=`echo $totaltime | awk '{print $3}'`

        sum_mean=`echo $sum_mean + $mean | bc`

        sd=`echo $totaltime | awk '{print $4}'`

        sum_sd=`echo $sum_sd + $sd | bc`

        echo "$HOST ${sum} ${sum_mean} ${sum_sd}" >> eva_all_$eva_case
done
